### ISSUE TITLE
CNAME source/sink doesn't get refreshed until Bandar-log restarts

### ISSUE THREAD

**Issue by alexey-kotlyar** [OneByAol/bandar-log#2]
Per https://github.com/brettwooldridge/HikariCP/issues/314, can be fixed pretty quickly by adding `networkaddress.cache.ttl` property with a relatively small default value, like `10` [seconds].

**Comment by alexey-lipodat** [comment]
We can resolve this issue by adding `-Dsun.net.inetaddr.ttl=10` JVM option.
_Example:_
```
docker run --name tagged onebyaol/bandarlog:latest --config-path "https://config.path.example/application.conf" -Dsun.net.inetaddr.ttl=10
```
