### ISSUE TITLE
Add Athena/Glue support

### ISSUE THREAD

**Issue by denis-pyshev** [OneByAol/bandar-log#5]
We need to monitor metrics on Athena, so Bandar-log needs Athena/Glue SQL data source support.
Keep in mind the method of obtaining max(batch_id) specific to AWS Glue to not do full scan of target table.

**Comment by MariiaRa** [comment]
Suggested steps: 
1) Dependency we need: Athena Driver; AWS-java-sdk (glue)
2) Create AthenaConnector interface to describe basic db access logic
3) Implement AthenaConnector interface, for obtaining max_batch_id use Glue client

**Comment by denis-pyshev** [comment]
OneByAol/bandar-log/pull/6

**Comment by denis-pyshev** [comment]
Ready, tested and merged.
